export default {
  appointments: [],
  caseFiles: [],
  procedures: [],
  physicians: [],
  storage: [],
  theatres: [],
  inventory: [],
  equipment: [],
  equipmentTypyes: [],
  suppliers: [],
  orders: [],
  cart: [],
  notifications: [],
  auth: {
    isLoading: true,
    isSignOut: false,
    userToken: null,
    expoPushToken: null,
    user: {},
  },
  draft: [],
  archivedSuppliers: [],
  archivedCases: [],
  casePage: { isEdit: false, procedureEndTime: "" },
  procedurePage: { isEdit: false },
  invoices: [],
};
